[package]
name = "calmdown"
version = "1.0.0"
authors = ["Hyeonu Park <nemo1275@gmail.com>"]
edition = "2018"
description = "Fails if the directory is modified too recently"
license = "Unlicense OR MIT"

[dependencies]
structopt = "0.3"
ignore = "0.4"
humantime = "1.3"
